apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service-deployment
  labels:
    app: demo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      labels:
        app: demo-service
    spec:
      containers:
      - name: demo-service
        image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/demo_codebuild:0000000000000000000000000000000000000000
        ports:
        - containerPort: 18080
