apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: demo
    app: demo-service
  name: demo-service
spec:
  ports:
  - name: http
    port: 18080
    protocol: TCP
    targetPort: 18080
  selector:
    app: demo-service
  type: ClusterIP
status:
  loadBalancer: {}
